# Move Package Configuration for Optimus - Simple Version

[package]
name = "Optimus"
version = "1.0.0"

[addresses]
stake_pool_addr = "0xc367c4aefe1bc6028e0a5981c63c85347fcde2547f487904addc6762f8b130de"
initial_reward_creator_addr = "0xc367c4aefe1bc6028e0a5981c63c85347fcde2547f487904addc6762f8b130de"
fa_obj_addr = "0xa"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"